restructure go install

diff --git a/home/run_onchange_after_install-go-tools.sh.tmpl b/home/run_onchange_after_install-go-tools.sh.tmpl
--- a/home/run_onchange_after_install-go-tools.sh.tmpl
+++ b/home/run_onchange_after_install-go-tools.sh.tmpl
@@ -14,6 +14,6 @@ for pkg in \
     golang.org/x/tools/cmd/goimports@latest
 do
     echo "installing ${pkg%@*}"
-    go install "$pkg"
+    go install "$pkg" || echo "failed: $pkg" >&2
 done
 
